tasty_bytes:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: sysadmin
      database: glen_dbt_dev
      schema: dbt_dev
      warehouse: compute_wh
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: sysadmin
      database: glen_dbt_dev
      schema: dbt_prod
      warehouse: compute_wh
